CREATE TABLE szamla (
ESST_ID BIGINT NOT NULL,
X_BRUTTO_HUF BIGINT NOT NULL,
KATEGORIA VARCHAR(100) NOT NULL,
V_ADOSZAM_TORZSSZAM_DEP BIGINT NOT NULL,
PRIMARY KEY (V_ADOSZAM_TORZSSZAM_DEP, ESST_ID, KATEGORIA),
FOREIGN KEY (V_ADOSZAM_TORZSSZAM_DEP) REFERENCES gazdmut(AA_AZON)
ON UPDATE CASCADE
ON DELETE NO ACTION
);