CREATE TABLE szamla (
id BIGINT PRIMARY KEY AUTO_INCREMENT,
ESST_ID BIGINT NOT NULL,
X_BRUTTO_HUF BIGINT NOT NULL,
KATEGORIA VARCHAR(100) NOT NULL,
V_ADOSZAM_TORZSSZAM_DEP BIGINT NOT NULL,
FOREIGN KEY (V_ADOSZAM_TORZSSZAM_DEP) REFERENCES gazdmut(AA_AZON)
ON UPDATE CASCADE ON DELETE NO ACTION
);